import type { CollectionConfig } from 'payload'

export const Products: CollectionConfig = {
  slug: 'products',
  admin: { group: 'Catalog', useAsTitle: 'name', defaultColumns: ['name', 'sku', 'price', 'isActive'] },
  fields: [
    { name: 'name', type: 'text', required: true, localized: true },
    { name: 'slug', type: 'text', required: true, unique: true, index: true },
    { name: 'sku', type: 'text', required: true, unique: true },
    { name: 'partNumber', type: 'text' },
    { name: 'description', type: 'richText', localized: true },
    { name: 'shortDescription', type: 'textarea', localized: true },
    { name: 'price', type: 'number', required: true, min: 0 },
    { name: 'compareAtPrice', type: 'number', min: 0 },
    { name: 'stock', type: 'number', defaultValue: 0, min: 0 },
    { name: 'weight', type: 'number' },
    { name: 'thumbnail', type: 'upload', relationTo: 'media' },
    {
      name: 'images',
      type: 'array',
      fields: [{ name: 'image', type: 'upload', relationTo: 'media' }],
    },
    { name: 'brand', type: 'relationship', relationTo: 'brands' },
    { name: 'category', type: 'relationship', relationTo: 'categories' },
    {
      name: 'compatibleVehicles',
      type: 'relationship',
      relationTo: 'ymmts',
      hasMany: true,
    },
    {
      name: 'variantType',
      type: 'select',
      defaultValue: 'simple',
      options: [
        { label: 'Simple', value: 'simple' },
        { label: 'Parent', value: 'parent' },
        { label: 'Variation', value: 'variation' },
      ],
    },
    { name: 'variationType', type: 'text' },
    { name: 'variationValue', type: 'text' },
    { name: 'isActive', type: 'checkbox', defaultValue: true },
    { name: 'isFeatured', type: 'checkbox', defaultValue: false },
    // Dynamic attributes
    { name: 'attribute1Name', type: 'text' },
    { name: 'attribute1Value', type: 'text' },
    { name: 'attribute2Name', type: 'text' },
    { name: 'attribute2Value', type: 'text' },
    { name: 'attribute3Name', type: 'text' },
    { name: 'attribute3Value', type: 'text' },
    { name: 'attribute4Name', type: 'text' },
    { name: 'attribute4Value', type: 'text' },
    { name: 'attribute5Name', type: 'text' },
    { name: 'attribute5Value', type: 'text' },
    { name: 'attribute6Name', type: 'text' },
    { name: 'attribute6Value', type: 'text' },
    { name: 'attribute7Name', type: 'text' },
    { name: 'attribute7Value', type: 'text' },
    { name: 'attribute8Name', type: 'text' },
    { name: 'attribute8Value', type: 'text' },
    { name: 'attribute9Name', type: 'text' },
    { name: 'attribute9Value', type: 'text' },
    { name: 'attribute10Name', type: 'text' },
    { name: 'attribute10Value', type: 'text' },
  ],
  access: { read: () => true },
}
