/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    categories: Category;
    brands: Brand;
    ymmts: Ymmt;
    vehicles: Vehicle;
    orders: Order;
    'order-items': OrderItem;
    transactions: Transaction;
    addresses: Address;
    provinces: Province;
    pages: Page;
    menus: Menu;
    'hero-sections': HeroSection;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    ymmts: YmmtsSelect<false> | YmmtsSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'hero-sections': HeroSectionsSelect<false> | HeroSectionsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    'site-identity': SiteIdentity;
    'store-information': StoreInformation;
    'checkout-settings': CheckoutSetting;
  };
  globalsSelect: {
    'site-identity': SiteIdentitySelect<false> | SiteIdentitySelect<true>;
    'store-information': StoreInformationSelect<false> | StoreInformationSelect<true>;
    'checkout-settings': CheckoutSettingsSelect<false> | CheckoutSettingsSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  customerType?: ('individual' | 'business' | 'dealer') | null;
  companyName?: string | null;
  role?: ('admin' | 'customer') | null;
  marketingOptIn?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  partNumber?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  price: number;
  compareAtPrice?: number | null;
  stock?: number | null;
  weight?: number | null;
  thumbnail?: (string | null) | Media;
  images?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  brand?: (string | null) | Brand;
  category?: (string | null) | Category;
  compatibleVehicles?: (string | Ymmt)[] | null;
  variantType?: ('simple' | 'parent' | 'variation') | null;
  variationType?: string | null;
  variationValue?: string | null;
  isActive?: boolean | null;
  isFeatured?: boolean | null;
  attribute1Name?: string | null;
  attribute1Value?: string | null;
  attribute2Name?: string | null;
  attribute2Value?: string | null;
  attribute3Name?: string | null;
  attribute3Value?: string | null;
  attribute4Name?: string | null;
  attribute4Value?: string | null;
  attribute5Name?: string | null;
  attribute5Value?: string | null;
  attribute6Name?: string | null;
  attribute6Value?: string | null;
  attribute7Name?: string | null;
  attribute7Value?: string | null;
  attribute8Name?: string | null;
  attribute8Value?: string | null;
  attribute9Name?: string | null;
  attribute9Value?: string | null;
  attribute10Name?: string | null;
  attribute10Value?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  logo?: (string | null) | Media;
  website?: string | null;
  brandType?: ('vehicle' | 'parts' | 'both') | null;
  isActive?: boolean | null;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  displayName?: string | null;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  image?: (string | null) | Media;
  /**
   * CSS icon class name
   */
  icon?: string | null;
  /**
   * Hex color code
   */
  color?: string | null;
  categoryType: 'product' | 'parts' | 'accessories' | 'clothing' | 'helmets' | 'blog';
  parent?: (string | null) | Category;
  vehicleTypes?: ('atv' | 'utv' | 'snowmobile' | 'motorcycle' | 'watercraft' | 'marine')[] | null;
  isActive?: boolean | null;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ymmts".
 */
export interface Ymmt {
  id: string;
  year: number;
  make: string | Brand;
  model: string;
  submodel?: string | null;
  trim?: string | null;
  engineCode?: string | null;
  vehicleType: 'atv' | 'utv' | 'snowmobile' | 'motorcycle' | 'pwc' | 'marine';
  displayName?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: string;
  title: string;
  slug: string;
  stockNumber?: string | null;
  condition: 'new' | 'used' | 'certified';
  vehicleType: 'atv' | 'utv' | 'snowmobile' | 'motorcycle' | 'watercraft' | 'spyder';
  brand?: (string | null) | Brand;
  year?: number | null;
  model?: string | null;
  trim?: string | null;
  mileage?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price?: number | null;
  thumbnail?: (string | null) | Media;
  images?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber: string;
  customer?: (string | null) | User;
  email: string;
  status?: ('pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded') | null;
  paymentStatus?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  stripePaymentIntentId?: string | null;
  subtotal: number;
  taxAmount: number;
  shippingAmount: number;
  discountAmount?: number | null;
  total: number;
  items?: (string | OrderItem)[] | null;
  shippingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  billingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  shippingMethod?: string | null;
  trackingNumber?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: string;
  order?: (string | null) | Order;
  product?: (string | null) | Product;
  productName: string;
  sku?: string | null;
  quantity: number;
  price: number;
  total: number;
  variationType?: string | null;
  variationValue?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  transactionId?: string | null;
  order?: (string | null) | Order;
  type?: ('payment' | 'refund' | 'authorization' | 'capture' | 'void') | null;
  status?: ('pending' | 'completed' | 'failed' | 'cancelled') | null;
  amount: number;
  currency?: string | null;
  provider?: ('stripe' | 'paypal' | 'cash' | 'other') | null;
  providerTransactionId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  user: string | User;
  firstName: string;
  lastName: string;
  company?: string | null;
  address1: string;
  address2?: string | null;
  city: string;
  province?: (string | null) | Province;
  postalCode: string;
  country?: string | null;
  phone?: string | null;
  type?: ('billing' | 'shipping' | 'both') | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: string;
  name: string;
  code: string;
  country?: string | null;
  taxRate?: number | null;
  gstRate?: number | null;
  pstRate?: number | null;
  hstRate?: number | null;
  qstRate?: number | null;
  shippingZone?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  template?:
    | (
        | 'custom'
        | 'home'
        | 'about'
        | 'contact'
        | 'service'
        | 'blog'
        | 'legal'
        | 'mega-menu-item-landing'
        | 'vehicles-new'
        | 'vehicles-used'
      )
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  featuredImage?: (string | null) | Media;
  seoTitle?: string | null;
  seoDescription?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  name: string;
  slug: string;
  location:
    | 'topbar-right'
    | 'main-navigation'
    | 'footer-left'
    | 'footer-center'
    | 'footer-right'
    | 'footer-bottom'
    | 'mobile-main'
    | 'mobile-secondary';
  items?:
    | {
        label: string;
        type?: ('internal' | 'external' | 'category' | 'page' | 'megamenu') | null;
        url?: string | null;
        page?: (string | null) | Page;
        category?: (string | null) | Category;
        openInNewTab?: boolean | null;
        highlight?: boolean | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-sections".
 */
export interface HeroSection {
  id: string;
  name: string;
  location?: ('homepage' | 'category' | 'promotion' | 'seasonal') | null;
  pageSlug?: string | null;
  slides?:
    | {
        title?: string | null;
        subtitle?: string | null;
        buttonText?: string | null;
        buttonLink?: string | null;
        backgroundImage: string | Media;
        overlayOpacity?: number | null;
        textAlignment?: ('left' | 'center' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  autoPlay?: boolean | null;
  autoPlayDelay?: number | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  startDate?: string | null;
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  formType: 'contact' | 'career' | 'vehicle-inquiry' | 'parts-request' | 'newsletter';
  firstName?: string | null;
  lastName?: string | null;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('new' | 'read' | 'replied' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'ymmts';
        value: string | Ymmt;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: string | Vehicle;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: string | OrderItem;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'provinces';
        value: string | Province;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'menus';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'hero-sections';
        value: string | HeroSection;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  customerType?: T;
  companyName?: T;
  role?: T;
  marketingOptIn?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sku?: T;
  partNumber?: T;
  description?: T;
  shortDescription?: T;
  price?: T;
  compareAtPrice?: T;
  stock?: T;
  weight?: T;
  thumbnail?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  brand?: T;
  category?: T;
  compatibleVehicles?: T;
  variantType?: T;
  variationType?: T;
  variationValue?: T;
  isActive?: T;
  isFeatured?: T;
  attribute1Name?: T;
  attribute1Value?: T;
  attribute2Name?: T;
  attribute2Value?: T;
  attribute3Name?: T;
  attribute3Value?: T;
  attribute4Name?: T;
  attribute4Value?: T;
  attribute5Name?: T;
  attribute5Value?: T;
  attribute6Name?: T;
  attribute6Value?: T;
  attribute7Name?: T;
  attribute7Value?: T;
  attribute8Name?: T;
  attribute8Value?: T;
  attribute9Name?: T;
  attribute9Value?: T;
  attribute10Name?: T;
  attribute10Value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  displayName?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  image?: T;
  icon?: T;
  color?: T;
  categoryType?: T;
  parent?: T;
  vehicleTypes?: T;
  isActive?: T;
  isFeatured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  website?: T;
  brandType?: T;
  isActive?: T;
  isFeatured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ymmts_select".
 */
export interface YmmtsSelect<T extends boolean = true> {
  year?: T;
  make?: T;
  model?: T;
  submodel?: T;
  trim?: T;
  engineCode?: T;
  vehicleType?: T;
  displayName?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  stockNumber?: T;
  condition?: T;
  vehicleType?: T;
  brand?: T;
  year?: T;
  model?: T;
  trim?: T;
  mileage?: T;
  description?: T;
  price?: T;
  thumbnail?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  isActive?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  email?: T;
  status?: T;
  paymentStatus?: T;
  stripePaymentIntentId?: T;
  subtotal?: T;
  taxAmount?: T;
  shippingAmount?: T;
  discountAmount?: T;
  total?: T;
  items?: T;
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        address1?: T;
        address2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        address1?: T;
        address2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        country?: T;
      };
  shippingMethod?: T;
  trackingNumber?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  productName?: T;
  sku?: T;
  quantity?: T;
  price?: T;
  total?: T;
  variationType?: T;
  variationValue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  transactionId?: T;
  order?: T;
  type?: T;
  status?: T;
  amount?: T;
  currency?: T;
  provider?: T;
  providerTransactionId?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  user?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  address1?: T;
  address2?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  type?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  country?: T;
  taxRate?: T;
  gstRate?: T;
  pstRate?: T;
  hstRate?: T;
  qstRate?: T;
  shippingZone?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  template?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        category?: T;
        openInNewTab?: T;
        highlight?: T;
        icon?: T;
        id?: T;
      };
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-sections_select".
 */
export interface HeroSectionsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  pageSlug?: T;
  slides?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonText?: T;
        buttonLink?: T;
        backgroundImage?: T;
        overlayOpacity?: T;
        textAlignment?: T;
        id?: T;
      };
  autoPlay?: T;
  autoPlayDelay?: T;
  isActive?: T;
  sortOrder?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  metadata?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-identity".
 */
export interface SiteIdentity {
  id: string;
  siteName: string;
  tagline?: string | null;
  logo?: (string | null) | Media;
  /**
   * Logo for dark backgrounds
   */
  logoDark?: (string | null) | Media;
  favicon?: (string | null) | Media;
  defaultOgImage?: (string | null) | Media;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    tiktok?: string | null;
  };
  seo?: {
    defaultTitle?: string | null;
    titleSuffix?: string | null;
    defaultDescription?: string | null;
    defaultKeywords?: string | null;
  };
  analytics?: {
    googleAnalyticsId?: string | null;
    googleTagManagerId?: string | null;
    facebookPixelId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-information".
 */
export interface StoreInformation {
  id: string;
  storeName: string;
  legalName?: string | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    tollFree?: string | null;
    fax?: string | null;
  };
  address?: {
    street?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  hours?:
    | {
        day?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
        open?: string | null;
        close?: string | null;
        isClosed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  currency?: {
    code?: string | null;
    symbol?: string | null;
  };
  tax?: {
    enabled?: boolean | null;
    includedInPrices?: boolean | null;
    defaultProvince?: (string | null) | Province;
    gstNumber?: string | null;
    qstNumber?: string | null;
  };
  shipping?: {
    freeShippingThreshold?: number | null;
    defaultShippingRate?: number | null;
    handlingTime?: string | null;
  };
  policies?: {
    shippingPolicy?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    returnPolicy?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    privacyPolicy?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    termsOfService?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-settings".
 */
export interface CheckoutSetting {
  id: string;
  guestCheckoutEnabled?: boolean | null;
  minimumOrderAmount?: number | null;
  paymentMethods?: {
    stripeEnabled?: boolean | null;
    paypalEnabled?: boolean | null;
  };
  checkoutLabels?: {
    stepShippingTitle?: string | null;
    stepPaymentTitle?: string | null;
    stepConfirmTitle?: string | null;
    orderSummaryTitle?: string | null;
    placeOrderButton?: string | null;
    subtotalLabel?: string | null;
    shippingLabel?: string | null;
    taxLabel?: string | null;
    totalLabel?: string | null;
    freeShippingMessage?: string | null;
  };
  termsPage?: (string | null) | Page;
  privacyPage?: (string | null) | Page;
  successMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-identity_select".
 */
export interface SiteIdentitySelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  defaultOgImage?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        youtube?: T;
        linkedin?: T;
        tiktok?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        titleSuffix?: T;
        defaultDescription?: T;
        defaultKeywords?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
        facebookPixelId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-information_select".
 */
export interface StoreInformationSelect<T extends boolean = true> {
  storeName?: T;
  legalName?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        tollFree?: T;
        fax?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        country?: T;
      };
  hours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        isClosed?: T;
        id?: T;
      };
  currency?:
    | T
    | {
        code?: T;
        symbol?: T;
      };
  tax?:
    | T
    | {
        enabled?: T;
        includedInPrices?: T;
        defaultProvince?: T;
        gstNumber?: T;
        qstNumber?: T;
      };
  shipping?:
    | T
    | {
        freeShippingThreshold?: T;
        defaultShippingRate?: T;
        handlingTime?: T;
      };
  policies?:
    | T
    | {
        shippingPolicy?: T;
        returnPolicy?: T;
        privacyPolicy?: T;
        termsOfService?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-settings_select".
 */
export interface CheckoutSettingsSelect<T extends boolean = true> {
  guestCheckoutEnabled?: T;
  minimumOrderAmount?: T;
  paymentMethods?:
    | T
    | {
        stripeEnabled?: T;
        paypalEnabled?: T;
      };
  checkoutLabels?:
    | T
    | {
        stepShippingTitle?: T;
        stepPaymentTitle?: T;
        stepConfirmTitle?: T;
        orderSummaryTitle?: T;
        placeOrderButton?: T;
        subtotalLabel?: T;
        shippingLabel?: T;
        taxLabel?: T;
        totalLabel?: T;
        freeShippingMessage?: T;
      };
  termsPage?: T;
  privacyPage?: T;
  successMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}